export let DATA = [{
    contentURL: 'interactive',
    contents: [{
       content: 'Our business was always kept under scrutiny. To guarantee a meticulous record, we kept record books in which all our expenses were put in. The one you are looking at is provided by the monastery’s archives. We want to bring its format and dimensions as well as its cover to your attention. The latter is made from an old, reused sheet of parchment, a recycling method, that was quite usual at the time. We now beseech you to tell us the accumulated value of travel costs and courier services the monastery had to pay for in the middle of the 15th century.',
       contentGer: 'Für das ordentliche Führen unserer Geschäfte wurden Rechnungsbücher angelegt. Darin wurden unsere Ausgaben in verschiedene Kategorien zusammengefasst und verzeichnet. Das vorliegende Beispiel stammt aus dem Archiv des Stiftes Klosterneuburg. Wir möchten dich nicht nur auf das Format und die Dicke dieses Buches hinweisen, sondern auch auf den für unsere Zeit nicht ungewöhnlichen Einband. Dieser besteht nur aus einem alten, wieder verwendetem Blatt Pergament. Wir wollen wissen, was das Stift Mitte des 15. Jahrhunderts für Boten und Reisen ausgegeben hat. Finde es für uns heraus!',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 71,
       locationId: 101,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      },{
       content: 'Minting of the bad coin \'Schinderling\'',
       contentGer: 'Prägung der minderwertigen Währung „Schinderlinge“',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 72,
       locationId: 101,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1458
      },{
       content: 'Parliament of Klosterneuburg',
       contentGer: 'Landtag in Korneuburg',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 73,
       locationId: 101,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1465
      },{
       content: 'Subversion by Hungarian Troops arround Vienna',
       contentGer: 'Zerstörungen durch ungarische Truppen rund um Wien',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 74,
       locationId: 101,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1477
      }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: 0,
    description: 'Explore transcription of accounting book',
    endDate: 1499,
    id: 101,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 8,
    locked: true,
    maxSeat: 999,
    parentId: 10,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1450,
    statusId: 3,
    titleENG: 'Coins and Governance',
    titleGER: 'Geld und Verwaltung',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'interactive',
    contents: [{
       content: 'Renaissance humanism started to spread throughout Europe and reached our archduchy by the middle of the 15th century. With the University of Vienna and our own court as the main places for this intellectual movement, some of the Augustinian Canons from Klosterneuburg had access to what is known as the seven liberal arts. They had been made a precondition to the studies of theology, medicine or law. One of the Augustinian Canons that studied in Vienna and manufactured his own books was Wolfgang Winthager. After finishing a course of studies, a certificate, that informed about one\'s determination was manufactured. An example can be seen here.',
       contentGer: 'In unserem Erzherzogtum hielt Mitte des 15. Jahrhunderts der Humanismus Einzug, dessen Zentren unser Hof und die Universität Wien war. Auch Chorherren aus Klosterneuburg studierten dort. Sie fertigten sich ihre Bücher für die Forschung selbst, wie etwa Wolfgang Winthager. An der Universität musste man übrigens zuerst die sieben freien Künste studieren, darunter Astronomie und Grammatik. Danach konnte man mit einem Studium in Medizin, Jura oder Theologie fortsetzen. Schloss man sein Studium ab, wurde dies oft in sogenannten Determinationsurkunden angekündigt. Eine kannst du hier bestaunen.',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 75,
       locationId: 102,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      },{
       content: 'Lecture held by the Augustinian Canons Wolfgang Winthager and Johannes Swarcz at the University of Vienna',
       contentGer: 'Vorlesungen der Chorherren Wolfgang Winthager und Johannes Swarcz an der Universität Wien',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 76,
       locationId: 102,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1450
      },{
       content: 'Ladislaus Sunthaym\'s final degree from the University of Vienna',
       contentGer: 'Studienabschluss Ladislaus Sunthayms an der Universität Wien',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 77,
       locationId: 102,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1465
      },{
       content: 'Call of Conrad Celtis to the University of Vienna',
       contentGer: 'Berufung Conrad Celtis\' an die Universität Wien',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 78,
       locationId: 102,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1497
      }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: 0,
    description: 'Solve exercise',
    endDate: 1499,
    id: 102,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 8,
    locked: true,
    maxSeat: 4,
    parentId: 10,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1450,
    statusId: 3,
    titleENG: 'Science and University',
    titleGER: 'Wissenschaft und Universität',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'tableat',
    contents: [{
       content: 'We, Maximilian demand your services, subject! We ordered our secretary Marx Treitzsauerwein, to write down our biography including all our heroic acts and achievements and have them printed. Help him finish our Weißkunig story! You will see some woodcut prints that were made by our court artist. Answer the questions correctly and you will be rewarded generously. Tell our story to our content and you will be promoted to the ranks of nobility.',
       contentGer: 'Wir, Maximilian, verlangen nun deine Dienste, Untertan! Wir haben unseren Sekretär, Marx Treitzsaurwein, damit beauftragt, unsere Lebensgeschichte mit all unseren Heldentaten und Errungenschaften niederzuschreiben und in Druck zu geben. Hilf unserem Sekretär, die Geschichte des Weißkunigs zu schreiben! Du wirst Holzschnitte sehen, die unsere Hofkünstler angefertigt haben. Beantworte die Fragen dazu richtig und du wirst reich belohnt werden. Vom Bettler wirst du zum Adeligen aufsteigen, wenn du in der Lage bist, unser Leben und unsere Taten so zu erzählen, wie wir sie gerne lesen möchten.',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 107,
       locationId: 301,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      },{
       content: 'Maximilian I is born.',
       contentGer: 'Geburt Maximilians I.',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 108,
       locationId: 301,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1459
      },{
       content: 'Maximilian takes part in the assembly of his empire',
       contentGer: 'Maximilian nimmt zum ersten Mal an einer Reichsversammlung teil',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 109,
       locationId: 301,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1471
      },{
       content: 'Marriage with Mary of Burgundy',
       contentGer: 'Heirat mit Maria von Burgund',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 110,
       locationId: 301,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1477
      }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: 0,
    description: 'Weyßkunig Quiz atLocation',
    endDate: 1519,
    id: 301,
    ipAddress: '10.10.11.3',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 6,
    locked: true,
    maxSeat: 999,
    parentId: 30,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1459,
    statusId: 2,
    titleENG: 'Weißkunig Quiz ',
    titleGER: 'Weißkunig Quiz ',
    unlockCoa: true,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'certo eh 2nd', /*interactive*/
    contents: [{
       content: 'Look at this! One of the eight splendid Sunthaym Panels. These sheets of parchment tell the story of 75 members of the Babenberg Family, men and women that are introduced by an initial, a marvelous decorated first letter. The capital G is the first letter of the colophon, which is a brief dedication statement. Position your mobile phone above the big initials to read the text.',
       contentGer: '',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 117,
       locationId: 402,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: 0,
    description: 'Doing something with panel',
    endDate: 1492,
    id: 402,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 8,
    locked: true,
    maxSeat: 4,
    parentId: 40,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1491,
    statusId: 2,
    titleENG: 'Understanding Sunthaym',
    titleGER: 'Sunthaym verstehen',
    unlockCoa: true,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'certo eh 1st', /* tableNotifyAt*/
    contents: [{
       content: 'Loyal subject, we love to be amused by miraculous storys. They keep us entertained while we are not out on a hunt. Go on, continue to please us with a good story. You shall be rewarded. As you know the Legend of the Veil is connected to the foundation of the Monastery of Klosterneuburg. Try to reenact it on this interaktive stage.',
       contentGer: 'Werter Untertan, wir hören gerne wundersame Geschichten. Dies vertreibt uns neben der Jagd unsere Zeit. Unterhalte uns mit einer spannenden Erzählung und du wirst belohnt! Um die Gründung des Stifts Klosterneuburg rankt sich die sogenannte "Schleierlegende". Versuche in diesem Spiel, diese Legende auf einer interaktiven Bühne nachzubauen!',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 118,
       locationId: 403,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      },{
       content: 'Mentioning of Saint Koloman in the Sunthaym Panels',
       contentGer: 'Erwähnung des heiligen Koloman in den Sunthaym-Tafeln',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 119,
       locationId: 403,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1491
      },{
       content: 'Illustration of the Legend of the Bow in the Babenberg Family Tree',
       contentGer: 'Abbildung der Bogenlegende auf dem Babenbergerstammbaum',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 120,
       locationId: 403,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1492
      },{
       content: 'The Frueauf Panels showing the Legend of the Veil are being manufactured',
       contentGer: 'Die Frueauf-Tafeln mit der Klosterneuburger Schleierlegende werden angefertigt',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 121,
       locationId: 403,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1505
      }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: 0,
    description: 'Legend game AtLocation',
    endDate: 1505,
    id: 403,
    ipAddress: '10.10.11.5',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 9,
    locked: true,
    maxSeat: 1,
    parentId: 40,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1491,
    statusId: 2,
    titleENG: 'Once upon a time..',
    titleGER: 'Es war einmal…',
    unlockCoa: true,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'interactive',
    contents: [{
       content: 'To grant our new Saint the honor he deserves, our father and we had him built a special shrine. For that occasion, our father requested silver to be worked into the coffin from our cousin Sigismund’s silver mines in Tyrol. Klosterneuburg was given the order to manufacture the artifact out of the precious raw materials that were provided by our smelting works in Tyrol. The splendid coffin weighed 436,5 Mark Silver and Leopold’s mortal remains found their final resting place in 1506.',
       contentGer: 'Um unsere Verehrung zu zeigen, wollten unser ehrwürdiger Vater und wir für den neuen Heiligen einen besonderen Schrein anfertigen lassen. Unser Vater versuchte sogar unseren Vetter Sigismund, welcher Regent unseres geliebten Landes Tirol war, zu überreden etwas Silber beizusteuern. Mit der Vergabe des Auftrages betrauten wir das Stift Klosterneuburg, dem wir dafür Geld aus unseren königlichen Schmelzhütten in Tirol zur Verfügung stellten. Der prachtvolle Sarg wog schließlich 436,5 Mark Silber und die Gebeine Leopolds fanden darin 1506 eine neue Ruhestätte.',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 128,
       locationId: 501,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: 0,
    description: 'Observe the inside of shrine',
    endDate: 1507,
    id: 501,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 8,
    locked: true,
    maxSeat: 4,
    parentId: 50,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1506,
    statusId: 2,
    titleENG: 'Final Resting Place',
    titleGER: 'Letzte Ruhestätte',
    unlockCoa: true,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
       content: 'Faithful subject, I shall now receive you in audience. You proved yourself a helpful servant while solving the riddles and you earned yourself a reward. In accordance with your rank you shall now be granted your personal coat of arms. Thus, you are made a member of our court and are privileged to explore additional premises. Proceed to the upper parts of the exhibition to learn more about our faible for memoria an earn additional parts to your coat of arms. You shall leave now!',
       contentGer: 'Getreuer Lieber, wir gewähren dir nun die Ehre, dich zur Audienz zu empfangen. Beim Lösen der Aufgaben hast du uns große Dienste erwiesen. Dies soll nicht unbelohnt bleiben: Deinem Stand gemäß verleihen wir dir jetzt dein persönliches Wappen. Damit wirst du Teil unserer erlesenen Hofgesellschaft und erhältst das Privileg, weitere Räumlichkeiten zu erkunden. Verfüge dich nun in den oberen Bereich der Ausstellung, um mehr über unser Bestreben nach Erinnerung zu erfahren! Möglicherweise erlangst du dadurch noch eine Aufwertung deines Wappens. Du darfst dich nun entfernen!',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 129,
       locationId: 5001,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1507,
    id: 5001,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 50,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1506,
    statusId: 1,
    titleENG: 'In Audience with the Emperor',
    titleGER: 'Audienz beim Kaiser',
    unlockCoa: true,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
       content: 'Loyal subject, it is we, Maximilian, who welcome you from up here, our throne. During your visit, you are going to be stunned by our regency as archduke of Austria and Emperor of the Holy Roman Empire and without doubt, by our fascinating history as a sovereign. The age we lived in may differ from yours but nevertheless it was a time of upheaval and change. Now let yourself be guided, by means of this app, and explore the late Middle Ages while exciting yourself with suspenseful riddles. Correct answers will win you parts of your personal coat of arms. A gift we will grant you at the end of your tour. Good Luck!',
       contentGer: 'Getreuer Untertan, wir, Maximilian, begrüßen dich hier vor unserem Thron. Bei deinem Besuch wirst du mehr über uns, den Erzherzog von Österreich und Kaiser des Heiligen Römischen Reichs, und unsere Geschichte erfahren. Die Zeit, in der wir gelebt haben, war anders als deine Zeit – aber auch sie war geprägt von Umbrüchen! Lass dich von dieser App durch das ausgehende Mittelalter leiten und löse dabei spannende Rätsel. Richtige Antworten schalten Bestandteile für dein persönliches Wappen frei, das wir dir später verleihen werden. Viel Erfolg!',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 68,
       locationId: 1000,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      },{
       content: 'Dear friend, it is nice to welcome you at this centre of erudition and scholarship! I, Ladislaus Sunthaym, have studied the family history of margrave Leopold III, the founder of this very monastery, Klosterneuburg. Emperor Maximilian himself asked me to produce a family tree out of my findings. What an honour to be part of his sage entourage. I very much love to share my wisdom: Let yourself be guided by me throughout the exhibition and help me solve the given riddles. Correct answers will win you parts of a personal coat of arms, which will be granted to you by the Emperor himself',
       contentGer: 'Werter Freund, schön, Sie hier in diesem Zentrum der Gelehrsamkeit begrüßen zu dürfen! Ich, Ladislaus Sunthaym, habe in Klosterneuburg die Familiengeschichte des Stiftsgründers Markgraf Leopold III. erforscht, nun möchte auch Kaiser Maximilian, dass ich einen Stammbaum für ihn anfertige. Was für eine Ehre in den Kreis seiner Gelehrten aufgenommen zu werden! Ich teile mein Wissen gerne: Lassen Sie sich von mir durch die Ausstellung leiten und helfen Sie mir dabei, Rätsel zu lösen! Richtige Antworten schalten Teile für Ihr persönliches Wappen frei, das Ihnen später vom Kaiser verliehen wird.',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 69,
       locationId: 1000,
       order: 1,
       storyTellerId: 2,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      },{
       content: 'Look at them, what a noble crowd: how they show off their jewels and precious gowns while attending their spiffing (grand) ceremonies. You might have already heard of me, Till Eulenspiegel is the name. I am not always a very welcomed guest as I love to play tricks and joke around. My spot is offstage, from where I can comment on all events. If you follow me through the exhibition, you will hear stories only a few elect know of. Let’s solve the given riddles together. Correct answers will reveal parts of a personal coat of arms, that his royal highness the emperor himself will grant to you. Maybe there will be time for some fooling around too… .',
       contentGer: 'Sieh sie dir an, die feinen Leute: Wie sie mit ihren Juwelen und teuren Gewändern angeben und prächtige Zeremonien vollführen! Vielleicht kennst du mich, ich heiße Till Eulenspiegel. Nicht immer bin ich gern gesehen, denn ich treibe oftmals Scherze. Mein Platz ist Abseits des Geschehens, das ich dennoch kommentiere: Wenn du mit mir durch die Ausstellung gehst, erfährst du Geschichten, die nicht jeder kennt. Lass uns gemeinsam Rätsel lösen! Richtige Antworten schalten Teile für dein eigenes Wappen frei, das dir später vom Kaiser verliehen wird. Vielleicht bleibt dabei Zeit für einen Scherz…',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 70,
       locationId: 1000,
       order: 1,
       storyTellerId: 3,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
       }],   
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'Intro to section 1:',
    endDate: 1499,
    id: 1000,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 5,
    locked: true,
    maxSeat: 1,
    parentId: 10,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1450,
    statusId: 1,
    titleENG: 'The Emperor\'s new Saint',
    titleGER: 'Des Kaisers neuer Heiliger',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
      content: 'Subject! Perceive with your own eyes how exciting and thrilling the 15th century was. A centennial that had everything in the mix: a good portion of political conflict, a dash of economic crises, a swirl of technical innovation, a good go of new intellectual movements and standards as well as a new saint for our archduchy of Austria, to the taste – what a time! But see for yourself! On the left you shall have all political turnpoints that made an impact on Klosterneuburg. To your right, you will follow the canonization of our estimated ancestor Leopold III',
      contentGer: 'Untertan! Siehe mit eigenen Augen, wie spannend und abwechslungsreich das 15. Jahrhundert war! Politische Machtkämpfe, wirtschaftliche Krisen, technische Neuerungen, neue geistige Strömungen und Bildungsideale sowie ein neuer Heiliger für unser Herzogtum Österreich – eine sehr faszinierende Mischung! Wir nehmen euch nun im nächsten Abschnitt auf eine Reise mit, die euch auf der linken Seite durch politische Wirren und ihren Einfluss auf Klosterneuburg führt. Parallel berichtet die rechte Seite von der Verehrung und Heiligsprechung unseres werten Vorfahren Leopolds III.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 79,
      locationId: 2000,
      order: 1,
      storyTellerId: 1,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'Oh, there is a very great deal to say about the 15th century, but as I always point out: information is best served in small portions. That is why I present you some of the most important political events concerning the archduchy of Austria to your left while you can follow the canonization of the Babenberg margrave Leopold III in 1485 to your right',
      contentGer: 'Über das 15. Jahrhundert gibt es viel zu erzählen – viel zu viel, als dass ich es Ihnen in kurzer Art und Weise erklären könnte. Das ist wirklich schade! Nun gut, ich habe mich dazu entschlossen, Ihnen auf der linken Seite des nächsten Ganges ein paar für das Herzogtum Österreich wichtige politische Ereignisse zu schildern, während es auf der rechten Seite um die Verehrung des babenbergischen Markgrafen Leopold III. und seine Heiligsprechung 1485 geht.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 80,
      locationId: 2000,
      order: 1,
      storyTellerId: 2,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
     content: 'Oh my, all this fuzz about politics and fighting and fancy emperors bores me to death! Go on, continue to be lulled to sleep by some dull facts on the left. Far more interesting is the story of Leopold III. Have you already heard about the legend of the veil, the origin myth of this very monastery or about the miracles that are attributed to Leopold? If you care for anecdotes about breathtaking love and miraculous wonders than stick to the right side of the hallway… so exciting!',
     contentGer: 'Tja, dieses ganze Gerede über Politik, Kämpfe und ach so tolle Herrscher langweilt mich! Viel lustiger und interessanter ist doch die Geschichte von Leopold III.! Kennt ihr schon die Schleierlegende, die Gründungslegende des Stiftes, in dem ihr gerade steht? Oder wisst ihr, welche tollen Wunder Leopold vollbracht hat? Also wenn ihr etwas über die öde Politik wissen wollt, dann seht euch auf der linken Seite um, und wenn ihr aber mehr für Geschichten und Wunder über habt, dann seid ihr auf der rechten Seite des Ganges richtig.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 81,
      locationId: 2000,
      order: 1,
      storyTellerId: 3,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'Intro to section 2:',
    endDate: 1507,
    id: 2000,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 5,
    locked: true,
    maxSeat: 1,
    parentId: 20,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1450,
    statusId: 1,
    titleENG: 'Conflict and Canonization',
    titleGER: 'Konflikt und Kanonisation',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
      content: 'Long before we, Maximilian, were born into this world, our family engaged in a feud. Brother stood against brother and the lordship was split. It took a great effort to end this bitter hostility for even our father Frederick III and his brother, our uncle Albert VI of Austria were bound to this vendetta. Their contention escalated in 1461 and took its toll on the territories below the river Enns. The rivalry finally ended with our uncle’s sudden death in 1463 and the installment of our father in his rightful place as sovereign of our beloved duchy of Austria.',
      contentGer: 'Lange vor unserer Geburt kam es in unserer Familie zu Zwistigkeiten. Bruder stellte sich gegen Bruder und was folgte war eine Teilung unseres Herrschaftsgebietes. Der Weg zur Wiedervereinigung war lang: auch unser Vater Kaiser Friedrich III. lag mit seinem Bruder, unserem Onkel Albrecht VI., im Disput. Die Streitigkeiten der beiden eskalierten 1461 und unter den bewaffneten Konflikten litt vor allem das Land unter der Enns. Der plötzliche Tod unseres Onkels 1463 beendete die Machtkämpfe und unser Vater wurde als rechtmäßiger Landesfürst unseres geliebten Herzogtums Österreich anerkannt.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 82,
      locationId: 2001,
      order: 1,
      storyTellerId: 1,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'In 1451 after the last direct heir of the Leopoldian bloodline died, political affairs became uncertain. The brothers Frederick III and duke Albert VI of Austria both claimed their right to the heritage and their already tense demenour culminated in an armed conflict in 1461. Klosterneuburg was in support of Albert VI, who in return tried to counteract the monastery’s economic strain by granting it privileges regarding trade and salt. The feud finally ended with the duke’s sudden death and Frederick III`s installment as sovereign in 1463.',
      contentGer: 'Die politische Lage im Herzogtum Österreich war nach dem Aussterben der leopoldinischen Linie im Jahr 1457 wieder unklar. Die Brüder Kaiser Friedrich III. und Herzog Albrecht VI. erhoben beide Anspruch auf das Erbe und die angespannte Situation entlud sich schließlich 1461 in einem bewaffneten Konflikt. Klosterneuburg unterstützte Albrecht VI., der im Gegenzug versuchte, den ökonomischen Belastungen Klosterneuburgs mit Handels- und Salzprivilegien entgegenzuwirken. Der Disput endete schließlich mit dem unerwarteten Tod Albrechts und der Anerkennung Friedrichs III. im Jahr 1463.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 83,
      locationId: 2001,
      order: 1,
      storyTellerId: 2,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'Schinderlings! What an infamous crime! As our sovereigns spent all the money fighting useless wars they started minting bad coins. All they were interested in was the expansion of their power and influence. Nobody cared about us, the suffering people. The silver in our shiny little pfennigs was replaced by a cheaper copper and lead, the worth of those coins was next to nothing. The result of this strike of genius was an unseen economic crisis. Thanks for nothing, my lords! But make no mistake I will get into your pockets, one way or another!',
      contentGer: 'Schinderlinge! Das war damals das eigentliche Verbrechen! Als unseren werten Herrschern das Geld für ihre Kriege und ihre Söldner ausging, ließen sie minderwertige Münzen prägen. Ihnen ging es nur um die Erweiterung ihrer Macht und sie dachten keineswegs an uns armes Volk! Das Silber unserer schönen Pfennige wurde also nach und nach durch Kupfer und Blei ersetzt. Sie waren dadurch kaum mehr etwas wert und die damit einhergehende Wirtschaftskrise könnt ihr euch gar nicht vorstellen! Vielen lieben Dank, meine Herrscher! Das Geld werde ich euch schon noch anderweitig aus der Tasche ziehen!',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 84,
      locationId: 2001,
      order: 1,
      storyTellerId: 3,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'Death of Ladislaus Postumus',
      contentGer: 'Tod von Ladislaus Postumus',
      contentLanguageId: 1,
      contentTypeId: 3,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 85,
      locationId: 2001,
      order: 2,
      storyTellerId: null,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: 1457
     },{
      content: 'Death of Albert VI of Austria',
      contentGer: 'Tod von Albrecht VI.',
      contentLanguageId: 1,
      contentTypeId: 3,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 86,
      locationId: 2001,
      order: 2,
      storyTellerId: null,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: 1463
     },{
      content: 'Outbreak of war between Frederick III and Matthias Corvinus',
      contentGer: 'Ausbruch des Krieges zwischen Friedrich III. und Matthias Corvinus',
      contentLanguageId: 1,
      contentTypeId: 3,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 87,
      locationId: 2001,
      order: 2,
      storyTellerId: null,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: 1477
     }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1493,
    id: 2001,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 20,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1450,
    statusId: 1,
    titleENG: 'Family Feud',
    titleGER: 'Familienzwist',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
      content: 'Margrave Leopold III was already worshipped shortly after his death. It was our father Frederick III, who once more initiated the canonization process in 1465 after our noble ancestor Rufolf IV had failed to do so before him. Pope Paul II instated a comission to investigate Leopold\'s miracle doings and to evaluate his candidacy. During the first papal investigation in Klosterneuburg in 1468, 191 loyal subjects were questioned. A number we are very proud of.',
      contentGer: 'Markgraf Leopold III. wurde zu Recht bereits kurz nach seinem Tod verehrt. Nach einem gescheiterten Heiligsprechungsversuch durch unseren edlen Vorfahren Rudolf IV. war es schließlich unser Vater Kaiser Friedrich III., der 1465 einen neuerlichen Kanonisationsprozess ins Rollen brachte. Papst Paul II. setzte eine Kommission ein, um die Wunder Leopolds zu untersuchen und um festzustellen, ob Leopold in den Kreis der Heiligen aufgenommen werden sollte. Beim ersten Zeugenverhör in Klosterneuburg 1468 erschienen 191 treue Untertanten, worauf wir besonders stolz sind!',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 95,
      locationId: 2002,
      order: 1,
      storyTellerId: 1,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'The worship of Babenberg margrave Leopold III began immediately after his death. Soon his tomb was sought by an increasing number of pilgrims and the now reigning house of Habsburg gained interest in this iconified monarch. Duke Rudolf IV, (called “the Founder”) initiated Leopold’s canonization but it was not until the reign of Frederick III that the papal commission started their investigation in 1468 and questioned over 240 individuals for the next two years. Their statements were put down in writing, authenticated by a notary public and sent to Rome for further inspections',
      contentGer: 'Der Babenberger Leopold III. wurde früh nach seinem Tod im Jahr 1136 verehrt. Sein Grab im Stift Klosterneuburg zog immer mehr Pilger an und auch das herrschende Geschlecht der Habsburger interessierte sich zunehmend für den Kult um Leopold. Herzog Rudolf IV. etwa setzte sich für die Heiligsprechung Leopolds ein, aber erst unter Kaiser Friedrich III. kam es zu Zeugenbefragungen durch eine päpstliche Untersuchungskommission. 1468, 1469 und 1470 wurden über 240 Menschen zu den Wundern Leopolds befragt, ihre Aussagen aufgezeichnet, notariell beglaubigt und zur Überprüfung nach Rom gesandt.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 96,
      locationId: 2002,
      order: 1,
      storyTellerId: 2,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'I must share with you the story of my most favorite miracle: there was a woman once that could barely make a living and one day she was forced to pawn her coat. Very soon afterwards the shylock demanded his money back but she was not able to pay him. In her time of need she turned to Leopold, who in her dream told her about a treasure. As she couldn’t find it while being awake Leopold came to her in her dreams once more. After her vision, she retrieved the promised treasure and could not only pay her debt but also make a living of it. Isn’t this wonderful? Hmmm… I think I should get some rest now… .',
      contentGer: 'Ich muss euch eines meiner liebsten Wunder erzählen: Eine Frau hatte Geldsorgen und sie war gezwungen ihren Mantel zu verpfänden. Der Pfandleiher forderte das Geld sehr bald zurück, sie konnte aber nicht bezahlen. Die Frau wandte sich an Leopold, der ihr schließlich im Traum erschien und von einem Schatz erzählte. Sie konnte ihn zunächst nicht finden und erst als ihr Leopold noch einmal erschienen war, fand sie die versprochenen Münzen. Damit konnte sie ihre Schulden bezahlen und es blieb ihr sogar noch Geld über. Ist dieses Wunder nicht toll? Ich glaube, ich gehe jetzt kurz schlafen.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 97,
      locationId: 2002,
      order: 1,
      storyTellerId: 3,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'Inquiry of the Witnesses in Klosterneuburg',
      contentGer: 'Zeugenbefragung in Klosterneuburg',
      contentLanguageId: 1,
      contentTypeId: 3,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 98,
      locationId: 2002,
      order: 2,
      storyTellerId: null,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: 1468
     },{
      content: 'Inquiry of the Witnesses in Klosterneuburg',
      contentGer: 'Zeugenbefragung in Klosterneuburg',
      contentLanguageId: 1,
      contentTypeId: 3,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 99,
      locationId: 2002,
      order: 2,
      storyTellerId: null,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: 1469
     },{
      content: 'Inquiry of the Witnesses at the Klosterneuburger Hof in Vienna',
      contentGer: 'Zeugenbefragung im Klosterneuburger Hof zu Wien',
      contentLanguageId: 1,
      contentTypeId: 3,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 100,
      locationId: 2002,
      order: 2,
      storyTellerId: null,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: 1470
     }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1470,
    id: 2002,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 20,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1468,
    statusId: 1,
    titleENG: 'Miracle and Witnesses',
    titleGER: 'Wunder und Zeugen',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
      content: 'After our father gained power King Matthias Corvinus of Hungary had the audacity to declare war on him in 1477. Corvinus united Hungary, secured the borders against the Ottoman Empire and invaded our territory below the Enns river! It was not until after Corvinus’ death in 1490 that formerly conquered areas were reunited with the rest of our archduchy. Despite all the unpleasantness he caused, he did support the canonization of Leopold III, we have to give him that.',
      contentGer: 'Nach dem Bruderzwist bedrohte der ungarische König Matthias Corvinus unser Herzogtum. Ihm gelang es Ungarn zu vereinen, seine Grenzen gegen die Türken zu sichern und mit seinen Truppen in unser Land unter der Enns einzumarschieren! Er hatte sich 1477 erdreistet, unserem Vater den Krieg zu erklären und erst durch Corvinus` Tod 1490 gelangten die eroberten Gebiete wieder in unsere Hände. Man muss diesem Mann aber zähneknirschend zugestehen, dass er nicht nur Leid über unser Herzogtum brachte, denn um sich Freunde zu machen, unterstützte er etwa den Heiligsprechungsprozess von Leopold III.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 88,
      locationId: 2003,
      order: 1,
      storyTellerId: 1,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'Matthias Corvinus was elected King of Hungary in 1458. Driven by his ambition he not only united the Hungarian Empire but conquered parts of the Duchy of Austria including Klosterneuburg in 1483 and Vienna in 1485. I have to admit that I am euqally impressed by his strategic thinking and his classical education as well as his love for arts. One of the erudites he counted amongst his entourage was the italian historiograph Antonio Bofini, who compiled a magnificent work on Hungary\'s History.',
      contentGer: 'Matthias Corvinus wurde 1458 zum ungarischen König gewählt. Von seinem Ehrgeiz getrieben konnte er nicht nur Ungarn einen, sondern auch Teile des Herzogtums Österreich erobern. Dazu zählten etwa 1483 Klosterneuburg oder 1485 Wien. Ich muss Ihnen sagen, dass ich nicht nur von seinen strategischen Leistungen beeindruckt bin, sondern auch von seiner humanistischen Bildung sowie seinem Interesse an Kunst und Kultur. Einer der Gelehrten, die er an seinem Hof um sich scharen konnte, war der italienische Historiograph Antonio Bonfini, der ein großartiges Werk über die ungarische Geschichte verfasste.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 89,
      locationId: 2003,
      order: 1,
      storyTellerId: 2,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'Oh these sovereigns! All they do is fight all day and try to outsmart each other! Who gathered the wiser erudites? Who\'s ancestors are the noblest? Who is the sharpest war-lord? As if I cared! The people were suffering. Klosterneuburg lost Wolfgang Wiesinger, may he rest in peace. His poor soul was swiped off this earth in the conflict between the Habsburgian sleepyhead Frederick III and the hungarian shooting star Matthias Corvinius.',
      contentGer: 'Diese Fürsten! Sie streiten immer nur untereinander und versuchen sich gegenseitig zu übertrumpfen! Wer hat die besseren Gelehrten um sich? Wer hat die edelsten Ahnen? Wer ist der größere Kriegsherr? Als würde mich das interessieren! Das Volk blutete. So etwa verlor der Klosterneuburger Wolfgang Wiesinger, Gott sei seiner Seele gnädig, dieser arme Tropf, sein Leben im Konflikt zwischen der habsburgischen Erzschlafmütze Friedrich III. und dem ungarischen Aufsteiger Matthias Corvinus.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 90,
      locationId: 2003,
      order: 1,
      storyTellerId: 3,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: ' Matthias Corvinus visits Vienna',
      contentGer: 'Matthias Corvinus besucht Wien',
      contentLanguageId: 1,
      contentTypeId: 3,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 91,
      locationId: 2003,
      order: 2,
      storyTellerId: null,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: 1470
     },{
      content: 'Klosterneuburg ist conquered by the Hungarians',
      contentGer: 'Klosterneuburg wird von den Ungarn eingenommen',
      contentLanguageId: 1,
      contentTypeId: 3,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 92,
      locationId: 2003,
      order: 2,
      storyTellerId: null,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: 1483
     },{
      content: 'Vienna is conquered by the Hungarians',
      contentGer: 'Ausbruch des Krieges zwischen Friedrich III. und Matthias Corvinus',
      contentLanguageId: 1,
      contentTypeId: 3,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 93,
      locationId: 2003,
      order: 2,
      storyTellerId: null,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: 1485
     },{
      content: 'Death of Matthias Corvinus in Vienna',
      contentGer: 'Tod von Matthias Corvinus in Wien',
      contentLanguageId: 1,
      contentTypeId: 3,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 94,
      locationId: 2003,
      order: 2,
      storyTellerId: null,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: 1490
     }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1490,
    id: 2003,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 20,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1470,
    statusId: 1,
    titleENG: 'Matthias Corvinus',
    titleGER: 'Matthias Corvinus',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
      content: 'Subject, patience is a virtue if not a principle and even a monarch has to live by it. Leopold’s canonization took forever. After the authenticated statements arrived in Rome, Pope Sixtus IV aborted the canonization process because of formalities and had it redone. It took another 15 years and an enormous financial effort until his successor Pope Innocent VIII finally recognized Leopold’s sanctity and included him in the Litany of the Saints.',
      contentGer: 'Untertanen, auch als Herrscher braucht man Geduld: Leopolds Heiligsprechungsprozess zog sich in die Länge. Nachdem die unterfertigten Aussagen der Zeugenbefragungen 1470 nach Rom gesandt worden waren, entschied Papst Sixtus IV., dass der Prozess aufgrund formaler Mängel abgebrochen und wiederholt werden musste. Dies war natürlich ein Rückschlag für unseren Vater und unser Erzherzogtum, doch sie gaben nicht auf! Es waren weitere 15 Jahre und hohe finanzielle Mittel notwendig, bis Papst Innozenz VIII. schließlich die Heiligkeit Leopolds anerkannte und ihn in das Verzeichnis der Heiligen aufnahm.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 101,
      locationId: 2004,
      order: 1,
      storyTellerId: 1,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'The canonization process was a complex one. The requirements for recognizing sanctity did not end with a person’s declared worthiness but had to fulfill formal standards. Latter being one of the reasons for Leopold’s declaration to take almost 20 years: bureaucratic errors, enormous costs and involved people dying slowed down the whole process. In the end, the defense speech held by Franciscus de Pavinis gave the final push. On January 6th, 1485 Leopold was recognized as a saint during a ceremonial act in St. Peter’s Basilica.',
      contentGer: 'Der Ablauf von Heiligsprechungsprozessen war komplex. Es musste nicht nur eindeutig nachgewiesen werden, dass die Person einer Heiligsprechung würdig war, sondern es mussten auch viele formale Kriterien eingehalten werden. Gründe, warum Leopolds Kanonisationsprozess 20 Jahre dauerte, waren unter anderem bürokratische Fehler, Todesfälle beteiligter Personen sowie sehr hohe Kosten. Am Ende half vor allem auch eine Verteidigungsrede zugunsten Leopolds, die von Franciscus de Pavinis verfasst wurde. Am 6. Jänner 1485 wurde Leopold während einer feierlichen Zeremonie im Petersdom heilig gesprochen.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 102,
      locationId: 2004,
      order: 1,
      storyTellerId: 2,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'Oh, look at him! This elegance! This grandeur! In full regalia of a margrave and wearing the hat of an archduke he looks just stunning. Between you and me: what you see is historically incorrect, because Leopold III was not an archduke but the painting would certainly miss something if the hat had been left out, don’t you think? And look there in his hand, the tiny model of the monastery, it always catches my attention. I am sure it is a symbol for his patronage of Klosterneuburg! Ah yes and the halo, very impressive indeed. I would fancy one too. Would fit me just right! Miracles do happen, you know!',
      contentGer: 'Sieh ihn dir an! Sieht er nicht herrschaftlich in seinem Markgrafen-Ornat und mit dem Erzherzogshut am Kopf aus? Unter uns: historisch richtig ist das nicht, denn Leopold III. war kein Erzherzog, aber wenn sie den Erzherzogshut einfach weggelassen hätten, würde dem Bild etwas fehlen, findest du nicht? Interessant finde ich ja auch das Stiftsmodell, das er in der Hand hält. Es steht sicher für seine Gründung von Klosterneuburg! Auch der Heiligenschein ist sehr beeindruckend – ob ich wohl auch mal so einen bekommen werde? Träumen darf man ja noch und wer weiß, vielleicht geschieht ja ein Wunder!',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 103,
      locationId: 2004,
      order: 1,
      storyTellerId: 3,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1508,
    id: 2004,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 20,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1507,
    statusId: 1,
    titleENG: 'Saint Leopold',
    titleGER: 'Der Heilige Leopold',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
      content: 'Now let us introduce our noble selves: born on the 22nd March 1459 in Wiener Neustadt to our father Frederick III, who had already been crowned Emperor of the Holy Roman Empire and our mother Eleonore of Portugal, a Portugese infanta. In 1486, we were crowned King of the Romans and seven years later in 1493 the Habsburg Hereditary Lands were put under our rule. At the Age of 49 in 1508 we had ourselves crowned Emperor of the Romans in Trient. Tu felix Austria nube! The unparalleled matrimonial policy we implied during our reign gained us the territories of Bohemia and Hungary.',
      contentGer: 'Wir, Maximilian, stellen uns vor: Geboren wurden wir am 22. März 1459 in Wiener Neustadt. Unser Vater Friedrich war zu dieser Zeit schon Kaiser des Heiligen Römischen Reichs. Unsere Mutter Eleonore kam von weit her: Sie war die Tochter des portugiesischen Königs. 1486 wurden wir zum römisch-deutschen König gekrönt, 1493 bekamen wir die Herrschaft über die habsburgischen Erblande und 1508 ließen wir uns in Trient zum römisch-deutschen Kaiser krönen. Eines der Glanzstücke unserer Regierung war unsere kluge Heiratspolitik, die unserem edlen Haus Habsburg Böhmen und Ungarn sicherte.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 104,
      locationId: 3000,
      order: 1,
      storyTellerId: 1,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'Let me introduce Maximilian’s branch of the family tree, I had produced for him. He was the son of Emperor Frederick III and Eleonora of Portugal. In 1477, he was married to Mary of Burgundy, whose father had just died. Maximilian, now also duke of Burgundy and his wife had two children: Philipp I, later King of Castile and Margeret, later Governor of the Habsburg Netherlands. Mary died in 1482 after only five years of marriage and Maximilian was remarried in 1494 to Bianca Maria Sforza. They had no children.',
      contentGer: 'Kaiser Maximilian hat mich beauftragt, einen Stammbaum für ihn anzufertigen. Lassen Sie uns damit beginnen! Maximilian ist der Sohn Kaiser Friedrichs III. und Eleonores von Portugal. 1477 heiratete er Maria von Burgund, deren Vater kurz zuvor gestorben war. So wurde Maximilian zum Herzog von Burgund. Viele Ideen, die er dort kennenlernte, flossen später in seine Regierung ein. Maria starb 1482, gemeinsam hatten sie zwei Kinder: Philipp, später König von Kastilien, und Margarete, später Statthalterin der habsburgischen Niederlande. 1494 heiratete er Bianca Maria Sforza, die Ehe blieb kinderlos.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 105,
      locationId: 3000,
      order: 1,
      storyTellerId: 2,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'Rumor has it, that a bright shining star appeared in the sky just as Maximilian was born in 1459. I know of another child, whose birth was accompanied by such an astronomic event – you sure know which: yes, of course Jesus. Well, I would call this a nice try to play the gallery, Maximilian. Chronicles and reports, that were not written by your erudites have no mention of such an event at all. But still such an announcement is odd, for medieval superstition read a comet as a bad omen.',
      contentGer: 'Ein Komet soll am Himmel erschienen sein, als Maximilian im Jahr 1459 geboren wurde. Ich kenne noch ein anderes Kind, dessen Geburt von einem Stern angekündigt wurde – du kannst dir sicher denken, welches… das Jesuskind. Tja, netter Versuch sich in Szene zu setzten, mein lieber Maximilian! In Chroniken und Berichten, die nicht von deinen Geschichtsschreibern stammen, ist nämlich keine Rede von einem Kometen. Es ist überhaupt ungewöhnlich, dass die Gelehrten Maximilians diesen Kometen erwähnten, denn im Spätmittelalter wurden Kometen zumeist als Vorzeichen für Katastrophen gedeutet!',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 106,
      locationId: 3000,
      order: 1,
      storyTellerId: 3,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'Intro to section 3:',
    endDate: 1577,
    id: 3000,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 5,
    locked: true,
    maxSeat: 1,
    parentId: 30,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1459,
    statusId: 1,
    titleENG: 'Maximilian I',
    titleGER: 'Maximilian I.',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
      content: 'The monastery of Klosterneuburg had a new saint to promote and the provost took good care of it. The first to be Jakob Paperl elected on the 1st July 1485. He inspired us with his conscientious work of keeping Leopold’s memory alive. Since his canonisation, the missals note the 15th November as Saint Leopold’s celebration day. Paintings, manuscripts and prints were made in his honor. Our committed erudite and genealogist Ladislaus Sunthaym produced a family tree. Listen to what he has to say!',
      contentGer: 'Nach der Heiligsprechung Leopolds III. setzte das Stift Klosterneuburg den Heiligen in Szene. Die Pröpste, allen voran der am 1. Juli 1485 gewählte Jakob Paperl, trieben diese Entwicklungen an und wir konnten dabei sogar Anregungen für unseren Hof finden. Seit der Heiligsprechung findet man in den Missalen am 15. November das Fest des Heiligen Leopold eingetragen. Außerdem entstanden Gemälde, Handschriften und Drucke, die sich mit Leopold beschäftigten. Einer der engagierten Gelehrten war unser späterer Genealoge, der dir bereits bekannt ist: Ladislaus Sunthaym. Sieh dir an, was er erzählt!',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 111,
      locationId: 4000,
      order: 1,
      storyTellerId: 1,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'After Leopold’s canonisation, I received the order to conduct a genealogical research on him. To do so I had to travel from one monastery to the next to consult and evaluate the available historical records. Scientific credibility is an unshakeable premise, but I just could not solve all of the puzzles. It was very challenging to find records regarding spouses and daughters and some relatives of the margrave have to remain without a name. Of course, I dedicated my hard work and findings to someone special. Who that is, I will tell you shortly.',
      contentGer: 'Nach der Heiligsprechung des Stiftsgründers habe ich den Auftrag angenommen, eine Genealogie Leopolds III. zu verfassen. Für dieses Vorhaben reiste ich von Kloster zu Kloster, um die historischen Aufzeichnungen einzusehen und zu bewerten. Es ist wichtig korrekt zu arbeiten, doch konnte ich so manches Rätsel nicht lösen. Von einigen Personen aus der Familie des Markgrafen sind keine Namen belegt. Sehr schwierig ist es auch, Aufzeichnungen über die Ehefrauen und Töchter zu finden. Wem ich den Text gewidmet habe, erzähle ich Ihnen gleich.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 112,
      locationId: 4000,
      order: 1,
      storyTellerId: 2,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'Good old Sunthaym worked himself to the bone to dust off the Babenberg’s genealogy. Way over the top, if you ask me. Nobody is ever going to read that, even more so if it is written on parchment and the letters are minuscule. The tablets that were made to illustrate the findings of Sunthaym were said to be kept behind bars – to read that you had to have eagle eyes. Talking of eagles: did you notice the funny animals around the tendrils? They are entertaining! Look there is an elephant, but what is it wearing? By the way: all the “Sunthaym tablets” can be seen in the upper parts of the exhibition.',
      contentGer: 'Der alte Sunthaym legte sich ja recht ins Zeug, um die verstaubte Geschichte der Babenberger auszugraben. Viel zu viel Aufwand, wenn du mich fragst. Das liest doch sowieso keiner, noch dazu, wenn die Geschichte in so kleiner Schrift auf Pergament geschrieben ist. Die hierfür angefertigten acht Tafeln sollen noch dazu hinter einem Gitter gehangen haben – um das zu lesen braucht man doch Adleraugen! Aber wenigstens die lustigen Tiere in den Ranken machen einem Freude, vor allem der Kriegselefant. Alle „Sunthaym-Tafeln“ findest du übrigens im oberen Bereich der Ausstellung.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 113,
      locationId: 4000,
      order: 1,
      storyTellerId: 3,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'Intro to section 4:',
    endDate: 1505,
    id: 4000,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 5,
    locked: true,
    maxSeat: 1,
    parentId: 40,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1485,
    statusId: 1,
    titleENG: 'The Monastery and the Provost',
    titleGER: 'Das Stift und der Propst',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
      content: 'Sunthayms work is very much to our satisfaction. Not only are these panels appealing in terms of content but also in terms of appearance. Perceive their beauty, subject! The origins and roots of our ancestors are adorned with decorations in gold and precious colors. A royal pedigree is always of uttermost importance. That is the reason why we asked Sunthaym to conduct the research on our family in the first place. He was not the only one working on this task.',
      contentGer: 'Die Arbeiten Sunthayms haben unser kaiserliches Interesse geweckt. Immerhin sind diese „Sunthaym-Tafeln“ nicht nur inhaltlich ansprechend, sondern sie sehen auch sehr prächtig aus! Gold und bunte Farben zieren die Herkunftsgeschichte unserer Vorfahren – wahrlich angemessen! Da die Herkunft für uns als Herrscher von besonderer Bedeutung ist, befahlen wir dem Gelehrten auch die Vergangenheit unserer edlen und altehrwürdigen Familie erforschen! Mit dieser ehrenwerten Aufgabe haben wir aber nicht nur ihn beauftragt, auch andere Personen arbeiteten diesbezüglich für uns.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 114,
      locationId: 4001,
      order: 1,
      storyTellerId: 1,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'Ah yes, the dedication! Of course, I dedicated all my work to the Holy Lord, the Virgin Mary and Saint Leopold himself. I am a clergyman for what it’s worth! But of course, I had to name Emperor Frederick and his son Maximilian and all their titles too as well as the Provost Jakob Paperl, they are my patrons. The manner in which I formulated this dedication can be seen a few steps farther. It’s all there in pure accuracy and extreme precision. It is as I always say: “Do it and do it right!”.',
      contentGer: 'Wem ich meine Genealogie gewidmet habe, möchten Sie wissen? Selbstverständlich Gott, der Jungfrau Maria und dem Heiligen Leopold, immerhin bin ich Geistlicher. Allerdings kam ich selbstverständlich nicht umhin, auch Kaiser Friedrich III. und seinen Sohn Maximilian hier zu erwähnen, und natürlich meinen Auftraggeber, den Propst Jakob Paperl. Wie ich diese Widmung formuliert habe, können Sie ein paar Schritte weiter sehen. Vielleicht klingt es ein wenig sperrig, aber die Titel der Herrscher konnte ich kaum kürzen. Es muss schließlich alles seine Richtigkeit haben, das verstehen Sie doch!',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 115,
      locationId: 4001,
      order: 1,
      storyTellerId: 2,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'What a bootlicker, this Sunthaym person! Everything is so neat and tidy! Look at it, of course he named God and the Sovereign and the Provost in his dedication, Mr. Perfect. This way he sure gained the Emperor’s goodwill. Me on the other hand, I prefer less effort and higher rewards. You doubt that I could pull that off? Go upstairs and see for yourself.',
      contentGer: 'Du meine Güte, was für ein Speichellecker dieser Sunthaym doch ist! Muss natürlich immer alles ganz korrekt machen; Gott, Herrscher und Auftraggeber brav nennen und ihnen alles recht machen. So hat er sogar die Gunst des Kaisers erlangt! Wenn du mich fragst, ich bin ja eher dafür, für wenig Aufwand, ordentlich verköstigt und bezahlt zu werden. Die Herrscher und Grundherren können sich’s doch ohnehin leisten, oder? Tatsächlich habe ich es oft geschafft, die Großen übers Ohr zu hauen. Wie mir das gelungen ist, erfährst du im oberen Teil der Ausstellung.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 116,
      locationId: 4001,
      order: 1,
      storyTellerId: 3,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1486,
    id: 4001,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 40,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1485,
    statusId: 1,
    titleENG: 'Sunthaym\'s research',
    titleGER: 'Sunthayms Forschungen',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
      content: 'Subject! Can you appreciate the splendor of these panels made by Rueland Frueauf the Younger? They show the legend regarding the foundation of the monastery by our ancestor Leopold III. He was a powerful ruler and a skilled hunter, just like us! It was during a hunt that he retrieved Agnes’ long before lost veil in an elderberry bush. The veil was undamaged and to complete this miraculous event, the Virgin Mother Mary appeared before him. In eternal thankfulness, he had Klosterneuburg built on the exact same spot.',
      contentGer: 'Untertan – sieh dir nur diese prächtigen Tafeln von Rueland Frueauf dem Jüngeren an! Sie zeigen die Legende der Gründung des Stiftes Klosterneuburg durch unseren Vorfahren Leopold III. Was für ein mächtiger Fürst er doch war und ein geschickter Jäger, wie auch wir einer sind! So war Leopold auch auf der Jagd, als er den Jahre zuvor verlorenen Schleier seiner Frau Agnes unversehrt in einem Holunderstrauch fand. Welch wundersames Ereignis, denn sogar die Mutter Gottes erschien ihm! Zum Dank ließ er an dieser Stelle das Stift Klosterneuburg erbauen.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 122,
      locationId: 4004,
      order: 1,
      storyTellerId: 1,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'These panels are the first to show us the legend regarding the foundation of the Monastery by our holy margrave in successive images, Rueland Frueauf the younger, signed it “RF”. The painter portrayed Leopold various times including the one with the margrave holding a model of the Monestary in his hands. The artist’s wife Dorothea is mentioned in the obituary.',
      contentGer: 'Diese Tafeln mit alten Malereien sind die ersten, die uns die Legende der Klostergründung durch den heiligen Markgrafen in mehreren Bildern vor Augen führen. Rueland Frueauf der Jünger hat sie mit ‚RF‘ signiert. Dieser Maler, der den heiligen Markgrafen nicht nur in diesem Werk ins Bild setzte, hat sich auch durch die große Tafel mit dem Heiligen und dem Modell der Stiftskirche verdient gemacht hat. Seine Frau Dorothea taucht übrigens in den Totenbüchern des Stiftes Klosterneuburg auf. Auch Ruelands Vater war Maler, er trug denselben Vornamen und wird Frueauf der Ältere genannt.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 123,
      locationId: 4004,
      order: 1,
      storyTellerId: 2,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'What a noble man on a noble steed and he is doing what noble men always do in their spare time, he hunts. I know nothing about hunting but I have a good feeling about those fierce men that are accompanying him and about the dogs. Look, they are there as Leopold retrieves Agnes’ veil. Rumor has it, that all the dogs, that were held in cages in Klosterneuburg are direct descendants of the canine companions that shared this holy moment.',
      contentGer: 'Ein edler Fürst, Markgraf Leopold auf der Jagd, könnt‘ er mich brauchen? Nun weiß ich mit Worten viel anzustellen, doch mit dem Spieß? Welch Glück, dass Leopolds Mannen unerschrocken waren und von einigen furchtlosen Jagdhunden begleitet wurden. Die bellenden Begleiter preschten wie uns die Bilder erzählen, in den Wald hinein und waren im Moment der Auffindung des Schleiers zugegen. Man erzählt sich, dass alle Hunde, die in den Zwingern in Klosterneuburg gehalten werden, von jenen abstammen, die bei dem heiligen Ereignis dabei waren.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 124,
      locationId: 4004,
      order: 1,
      storyTellerId: 3,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1506,
    id: 4004,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 40,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1505,
    statusId: 1,
    titleENG: 'The Legend of the Veil',
    titleGER: 'Die Schleierlegende',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
      content: 'What a fabulous day! On February 15, 1506, more than twenty years after his canonization Leopold’s remains were transferred during a relic translation ceremony. We amongst other members of our court and many of our subjects were present to be part of this exceptional occasion. We put a lot of thought into our wardrobe and decided to deliberately step away from waring our regalia and chose the robe of the archduke in respect to our holy ancestor and our beloved archduchy of Austria.',
      contentGer: 'Was für ein herausragender Tag! Am 15. Februar 1506 war es endlich soweit und mehr als 20 Jahre nach der Heiligsprechung unseres Vorfahren Leopolds III. kam es zu den Translationsfeierlichkeiten, also der Erhebung und der Umbettung seiner Gebeine. Diesem tollen Ereignis wohnten unzählige unserer Untertanen bei und natürlich nahmen auch wir an diesen Feierlichkeiten teil! Ganz bewusst entschieden wir uns an diesem Tag nicht, das uns zustehende königliche Ornat zu tragen, sondern im Gedenken an den Heiligen und für unser geliebtes Erzherzogtum Österreich wählten wir die erzherzogliche Kleidung.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 125,
      locationId: 5000,
      order: 1,
      storyTellerId: 1,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'The canonization process is officially brought to an end by a socalled relic translation ceremony during which the mortal remains of the recognized saint are transferred. In Leopold’s case this happened very late. First It was the Hungarians, who with their reign over Klosterneuburg made it impossible for the Habsburg family to take part in a ceremony and then it was King Maximilian I, who was wound up in his state’s affairs that he could not personally take part. That is why it head to be postponed until February 1505 but it sure was worth the wait!',
      contentGer: 'Erst durch die Translation, die zeremonielle Erhebung der Gebeine, fanden Heiligsprechungen ihren offiziellen Abschluss. Ich muss Ihnen sagen, dass die Translation in Leopolds Fall erst sehr spät stattfand. Zunächst lag es an der ungarischen Herrschaft über Klosterneuburg, die die Anwesenheit der habsburgischen Fürsten bei der Translation nicht zuließ und dann war König Maximilian I. zu sehr in die Geschäfte des Reiches verstrickt, um persönlich an den Feierlichkeiten teilzunehmen. Es musste bis Februar 1506 gewartet werden, doch dafür waren die Feierlichkeiten umso schöner!',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 126,
      locationId: 5000,
      order: 1,
      storyTellerId: 2,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'Boy, what a day! It was spectacular! All these people, the food, the atmosphere! Even the archduke showed himself even though he had a lot on his back lately! But hey I could make it so he should better make it too. After the canonization, they revealed the gigantic Babenberg family tree. I wonder where they left my invitation… ',
      contentGer: 'Was für ein Tag! Es war sensationell! Die Menschenmassen, das Essen, das Spektakel! Unser Erzherzog nahm trotz seiner ganzen Verpflichtungen auch an den Feierlichkeiten teil, aber mal ganz unter uns: wenn ich es schaffe, an diesem bedeutsamen Tag in Klosterneuburg zu sein, dann sollte es auch kein Problem für unseren Herrscher sein. Ihm wurde auch der nach der Heiligsprechung angefertigte, riesige Babenbergerstammbaum gezeigt. Meine Einladung dafür muss der Bote wohl verloren haben!',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 127,
      locationId: 5000,
      order: 1,
      storyTellerId: 3,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'Intro to section 5:',
    endDate: 1507,
    id: 5000,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 5,
    locked: true,
    maxSeat: 1,
    parentId: 50,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1506,
    statusId: 1,
    titleENG: 'Relocating the mortal remains',
    titleGER: 'Erhebung der Gebeine',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'tableNotifyAt',
    contents: [{
      content: 'There they are, the noble ancestors of the magnificent House of Habsburg. You can find Saint Leopold up there as well as some of his 18 children. His son Henry II of Austria, called Jasomirgott, was the first duke of Austria. All the other Babenbergs have interesting biographies too. Some were fighting wars, some set sail for the Holy Land, some mediated in terms of affairs regarding the Empire and others were married in order to broaden power and influence. Find out, when and where the Babenbergs lived, who they were married too and how they named their sons and daughters.',
      contentGer: 'Das sind sie, die edlen Ahnen unseres erlauchten Hauses Habsburg. Leopold der Heilige ist ebenso darauf zu finden wie einige seiner 18 Kinder. Sein Sohn Heinrich II., auch genannt Jasomirgott, wurde der erste Herzog Österreichs, aber auch die anderen Babenberger haben spannende Lebensgeschichten! Sie führten Kriege, stachen in See gen Heiliges Land, waren Vermittler in Reichsangelegenheiten und über Ehen kamen Verbindungen mit bedeutenden Fürstengeschlechtern zustande. Finde heraus, wann und wo die Babenberger lebten, mit wem sie verheiratet waren und wie ihre Töchter und Söhne hießen.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 130,
      locationId: 502,
      order: 1,
      storyTellerId: 1,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: 0,
    description: 'Genvis atLocation',
    endDate: 1507,
    id: 502,
    ipAddress: '10.10.11.6',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 9,
    locked: true,
    maxSeat: 2,
    parentId: 50,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1506,
    statusId: 2,
    titleENG: 'The Babenberg Pedigree',
    titleGER: 'Stammbaum der Babenberger',
    unlockCoa: true,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
      content: 'Subject, you have now laid eyes on the upper part of the exhibition. Tell me, are you impressed by all the ends and means we used to keep the memoria alive? By visiting this exhibition, you too guarantee the ongoing tradition of our memory, which we are very grateful for. As a final reward, we compensate you with the upgrade of your coat of arms. Wear it with pride and vigor. Make sure you are remembered!',
      contentGer: 'Untertan, nun hast du den oberen Teil der Ausstellung gesehen. Bist du beeindruckt von den Mühen, die wir auf uns genommen haben, um in Erinnerung zu bleiben? Unser Vorhaben war von Erfolg gekrönt. Mit dem Besuch der Ausstellung hast auch du unser gedacht, dafür sei dir unser höchster Dank ausgedrückt. Als Lohn steht dir eine Wappenbesserung zu. Führe dein Wappen mit Ehre und Stärke und merke dir eines: Sorg dafür, dass du nach deinem Tod nicht vergessen wirst!',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 131,
      locationId: 6000,
      order: 1,
      storyTellerId: 1,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'Intro to section',
    endDate: 1520,
    id: 6000,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 5,
    locked: true,
    maxSeat: 1,
    parentId: 60,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1519,
    statusId: 1,
    titleENG: 'Commemoration',
    titleGER: 'Totengedenken',
    unlockCoa: true,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
      content: 'Subject, it is time for us to leave this mortal world. You are going to mourn your emperor – this is our command! Messengers are going to spread the word of our death to the world and minstrels are going to sing songs about our greatness! Our funeral shall be modest: no splendour should touch our dead body, only ashes, lime and dirt. Break our teeth and crop our hair! Our death shall set an example of Christianity. We are not anymore afraid to be forgotten with the last chime: we made proper provisions to leave our own memory to posterity.',
      contentGer: 'Untertan, für uns ist es nun an der Zeit zu gehen. Du wirst deiner Pflicht gehorsam nachkommen, gebührend um deinen Herrscher zu trauern – so befehlen wir es dir! Boten werden unseren Tod im ganzen Land verkünden und auch Lieder wird es geben. Unser Begräbnis soll bescheiden sein: Keinen Prunk wollen wir an unserem toten Körper sehen, sondern Asche, Kalk und Erde. Brecht unsere Zähne aus und schert uns das Haar! Unser Tod soll ein christliches Exempel sein. Wir haben keine Angst mehr davor, mit dem letzten Glockenton zu verschwinden: Für unser Andenken in der Nachwelt haben wir gesorgt!',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 132,
      locationId: 6001,
      order: 1,
      storyTellerId: 1,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'In the Middle Ages, the awareness of dying was characterized by Christian philosophy. How people spent their lives determined whether they went to heaven or hell. Before going to heaven, most people had to spend some time in purgatory to atone for their sins. During their lifetimes, people gave money or other gifts to clerical and monastic institutions. In return, the clergymen prayed for the salvation of these people. Prayers and commemoration shortened the time someone had to spend in purgatory. A “good death” had to be well prepared whereas a sudden death was regarded as a “bad death”.',
      contentGer: 'Das Thema Sterben war im Mittelalter geprägt von der christlichen Weltanschauung. Der Lebensstil einer Person bestimmte, ob diese nach dem Tod in den Himmel oder in die Hölle kam. Als Vorstufe des Himmels hatten die meisten eine gewisse Zeit zur Buße der Sünden im Fegefeuer zu verbringen. Personen tätigten zu Lebzeiten Stiftungen an geistliche Institutionen, welche im Gegenzug für deren Seelenheil beteten. Denn Gebete und Erinnerung an einen Verstorbenen verkürzten dessen Zeit im Fegefeuer. Als „guter Tod“ galt übrigens ein wohl vorbereiteter Tod, „schlecht“ hingegen war ein plötzlicher Tod.',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 133,
      locationId: 6001,
      order: 1,
      storyTellerId: 2,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     },{
      content: 'I’ve recently heard a story about Maximilian: rumor has it that in the last years, he’s always travelled with a large wooden box or coffin. They say that this coffin contained books – for example the book “Theuerdank”, which tells the story of the emperor’s life. Once he had died, his entourage took the books out of the coffin and placed his corpse inside. They distributed the books that tell the emperor’s story. So, the life of the emperor’s body had ended, but his deeds came to life in the books and stories about him. Peculiar, isn’t it?',
      contentGer: 'Ich habe kürzlich eine Geschichte über Maximilian I. gehört: Er soll in seinen letzten Jahren stets eine Kiste oder einen Sarg auf seinen Reisen mitgeführt haben. In diesem Sarg sollen sich Bücher befunden haben – etwa der „Theuerdank“, der ja im Grunde die Geschichte des Kaisers erzählt. Als der Kaiser starb, nahm man die Bücher aus der Kiste heraus und legte den Leichnam hinein. Die Bücher mit der Geschichte Maximilians wurden verbreitet. So endete die Geschichte des kaiserlichen Körpers, jene der kaiserlichen Taten wurde aber in die Welt hinausgetragen. Skurril, findest du nicht?',
      contentLanguageId: 1,
      contentTypeId: 1,
      createdAt: '2019-09-10T21:34:02.000Z',
      id: 134,
      locationId: 6001,
      order: 1,
      storyTellerId: 3,
      updatedAt: '2019-09-10T21:34:02.000Z',
      year: null
     }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1519.5,
    id: 6001,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 60,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1519,
    statusId: 1,
    titleENG: 'Death and legacy',
    titleGER: 'Tod und Erinnerung',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   }];
