export let DATA = [{
    contentURL: 'interactive',
    contents: [{
       content: 'Our business was always kept under scrutiny. To guarantee a meticulous record, we kept record books in which all our expenses were put in. The one you are looking at is provided by the monastery’s archives. We want to bring its format and dimensions as well as its cover to your attention. The latter is made from an old, reused sheet of parchment, a recycling method, that was quite usual at the time. We now beseech you to tell us the accumulated value of travel costs and courier services the monastery had to pay for in the middle of the 15th century.',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 71,
       locationId: 101,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      },{
       content: 'Minting of the bad coin \'Schinderling\'',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 72,
       locationId: 101,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1458
      },{
       content: 'Parliament of Klosterneuburg',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 73,
       locationId: 101,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1465
      },{
       content: 'Subversion by Hungarian Troops arround Vienna',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 74,
       locationId: 101,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1477
      }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: 0,
    description: 'Explore transcription of accounting book',
    endDate: 1499,
    id: 101,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 8,
    locked: true,
    maxSeat: 999,
    parentId: 10,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1450,
    statusId: 3,
    titleENG: 'Coins and Governance',
    titleGER: 'Geld und Verwaltung',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'interactive',
    contents: [{
       content: 'Renaissance humanism started to spread throughout Europe and reached our archduchy by the middle of the 15th century. With the University of Vienna and our own court as the main places for this intellectual movement, some of the Augustinian Canons from Klosterneuburg had access to what is known as the seven liberal arts. They had been made a precondition to the studies of theology, medicine or law. One of the Augustinian Canons that studied in Vienna and manufactured his own books was Wolfgang Winthager. After finishing a course of studies, a certificate, that informed about one\'s determination was manufactured. An example can be seen here.',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 75,
       locationId: 102,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      },{
       content: 'Lecture held by the Augustinian Canons Wolfgang Winthager and Johannes Swarcz at the University of Vienna',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 76,
       locationId: 102,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1450
      },{
       content: 'Ladislaus Sunthaym\'s final degree from the University of Vienna',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 77,
       locationId: 102,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1465
      },{
       content: 'Call of Conrad Celtis to the University of Vienna',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 78,
       locationId: 102,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1497
      }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: 0,
    description: 'Solve exercise',
    endDate: 1499,
    id: 102,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 8,
    locked: true,
    maxSeat: 4,
    parentId: 10,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1450,
    statusId: 3,
    titleENG: 'Science and University',
    titleGER: 'Wissenschaft und Universität',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'tableat',
    contents: [{
       content: 'We, Maximilian demand your services, subject! We ordered our secretary Marx Treitzsauerwein, to write down our biography including all our heroic acts and achievements and have them printed. Help him finish our Weißkunig story! You will see some woodcut prints that were made by our court artist. Answer the questions correctly and you will be rewarded generously. Tell our story to our content and you will be promoted to the ranks of nobility.',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 107,
       locationId: 301,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      },{
       content: 'Maximilian I is born.',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 108,
       locationId: 301,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1459
      },{
       content: 'Maximilian takes part in the assembly of his empire',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 109,
       locationId: 301,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1471
      },{
       content: 'Marriage with Mary of Burgundy',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 110,
       locationId: 301,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1477
      }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: 0,
    description: 'Weyßkunig Quiz atLocation',
    endDate: 1519,
    id: 301,
    ipAddress: '10.10.11.3',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 6,
    locked: true,
    maxSeat: 999,
    parentId: 30,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1459,
    statusId: 2,
    titleENG: 'Weißkunig Quiz ',
    titleGER: 'Weißkunig Quiz ',
    unlockCoa: true,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'tableNotifyAt',
    contents: [{
       content: 'Loyal subject, we love to be amused by miraculous storys. They keep us entertained while we are not out on a hunt. Go on, continue to please us with a good story. You shall be rewarded. As you know the Legend of the Veil is connected to the foundation of the Monastery of Klosterneuburg. Try to reenact it on this interaktive stage.',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 118,
       locationId: 403,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      },{
       content: 'Mentioning of Saint Koloman in the Sunthaym Panels',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 119,
       locationId: 403,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1491
      },{
       content: 'Illustration of the Legend of the Bow in the Babenberg Family Tree',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 120,
       locationId: 403,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1492
      },{
       content: 'The Frueauf Panels showing the Legend of the Veil are being manufactured',
       contentLanguageId: 1,
       contentTypeId: 3,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 121,
       locationId: 403,
       order: 2,
       storyTellerId: null,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: 1505
      }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: 0,
    description: 'Legend game AtLocation',
    endDate: 1505,
    id: 403,
    ipAddress: '10.10.11.5',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 9,
    locked: true,
    maxSeat: 1,
    parentId: 40,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1491,
    statusId: 2,
    titleENG: 'Once upon a time..',
    titleGER: 'Es war einmal…',
    unlockCoa: true,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'interactive',
    contents: [{
       content: 'Look at this! One of the eight splendid Sunthaym Panels. These sheets of parchment tell the story of 75 members of the Babenberg Family, men and women that are introduced by an initial, a marvelous decorated first letter. The capital G is the first letter of the colophon, which is a brief dedication statement. Position your mobile phone above the big initials to read the text.',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 117,
       locationId: 402,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: 0,
    description: 'Doing something with panel',
    endDate: 1492,
    id: 402,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 8,
    locked: true,
    maxSeat: 4,
    parentId: 40,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1491,
    statusId: 2,
    titleENG: 'Understanding Sunthaym',
    titleGER: 'Sunthaym verstehen',
    unlockCoa: true,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'interactive',
    contents: [{
       content: 'To grant our new Saint the honor he deserves, our father and we had him built a special shrine. For that occasion, our father requested silver to be worked into the coffin from our cousin Sigismund’s silver mines in Tyrol. Klosterneuburg was given the order to manufacture the artifact out of the precious raw materials that were provided by our smelting works in Tyrol. The splendid coffin weighed 436,5 Mark Silver and Leopold’s mortal remains found their final resting place in 1506.',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 128,
       locationId: 501,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: 0,
    description: 'Observe the inside of shrine',
    endDate: 1507,
    id: 501,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 8,
    locked: true,
    maxSeat: 4,
    parentId: 50,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1506,
    statusId: 2,
    titleENG: 'Final Resting Place',
    titleGER: 'Letzte Ruhestätte',
    unlockCoa: true,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
       content: 'Faithful subject, I shall now receive you in audience. You proved yourself a helpful servant while solving the riddles and you earned yourself a reward. In accordance with your rank you shall now be granted your personal coat of arms. Thus, you are made a member of our court and are privileged to explore additional premises. Proceed to the upper parts of the exhibition to learn more about our faible for memoria an earn additional parts to your coat of arms. You shall leave now!',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 129,
       locationId: 5001,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      }],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1507,
    id: 5001,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 50,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1506,
    statusId: 1,
    titleENG: 'In Audience with the Emperor',
    titleGER: 'Audienz beim Kaiser',
    unlockCoa: true,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [{
       content: 'Loyal subject, it is we, Maximilian, who welcome you from up here, our throne. During your visit, you are going to be stunned by our regency as archduke of Austria and Emperor of the Holy Roman Empire and without doubt, by our fascinating history as a sovereign. The age we lived in may differ from yours but nevertheless it was a time of upheaval and change. Now let yourself be guided, by means of this app, and explore the late Middle Ages while exciting yourself with suspenseful riddles. Correct answers will win you parts of your personal coat of arms. A gift we will grant you at the end of your tour. Good Luck!',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 68,
       locationId: 1000,
       order: 1,
       storyTellerId: 1,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      },{
       content: 'Dear friend, it is nice to welcome you at this centre of erudition and scholarship! I, Ladislaus Sunthaym, have studied the family history of margrave Leopold III, the founder of this very monastery, Klosterneuburg. Emperor Maximilian himself asked me to produce a family tree out of my findings. What an honour to be part of his sage entourage. I very much love to share my wisdom: Let yourself be guided by me throughout the exhibition and help me solve the given riddles. Correct answers will win you parts of a personal coat of arms, which will be granted to you by the Emperor himself',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 69,
       locationId: 1000,
       order: 1,
       storyTellerId: 2,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
      },{
       content: 'Look at them, what a noble crowd: how they show off their jewels and precious gowns while attending their spiffing (grand) ceremonies. You might have already heard of me, Till Eulenspiegel is the name. I am not always a very welcomed guest as I love to play tricks and joke around. My spot is offstage, from where I can comment on all events. If you follow me through the exhibition, you will hear stories only a few elect know of. Let’s solve the given riddles together. Correct answers will reveal parts of a personal coat of arms, that his royal highness the emperor himself will grant to you. Maybe there will be time for some fooling around too… .',
       contentLanguageId: 1,
       contentTypeId: 1,
       createdAt: '2019-09-10T21:34:02.000Z',
       id: 70,
       locationId: 1000,
       order: 1,
       storyTellerId: 3,
       updatedAt: '2019-09-10T21:34:02.000Z',
       year: null
       }],   
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'Intro to section 1:',
    endDate: 1499,
    id: 1000,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 5,
    locked: true,
    maxSeat: 1,
    parentId: 10,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1450,
    statusId: 1,
    titleENG: 'The Emperor\'s new Saint',
    titleGER: 'Des Kaisers neuer Heiliger',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'Intro to section 2:',
    endDate: 1507,
    id: 2000,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 5,
    locked: true,
    maxSeat: 1,
    parentId: 20,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1450,
    statusId: 1,
    titleENG: 'Conflict and Canonization',
    titleGER: 'Konflikt und Kanonisation',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1493,
    id: 2001,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 20,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1450,
    statusId: 1,
    titleENG: 'Family Feud',
    titleGER: 'Familienzwist',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1470,
    id: 2002,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 20,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1468,
    statusId: 1,
    titleENG: 'Miracle and Witnesses',
    titleGER: 'Wunder und Zeugen',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1490,
    id: 2003,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 20,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1470,
    statusId: 1,
    titleENG: 'Matthias Corvinus',
    titleGER: 'Matthias Corvinus',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1508,
    id: 2004,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 20,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1507,
    statusId: 1,
    titleENG: 'Saint Leopold',
    titleGER: 'Der Heilige Leopold',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'Intro to section 3:',
    endDate: 1577,
    id: 3000,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 5,
    locked: true,
    maxSeat: 1,
    parentId: 30,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1459,
    statusId: 1,
    titleENG: 'Maximilian I',
    titleGER: 'Maximilian I.',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'Intro to section 4:',
    endDate: 1505,
    id: 4000,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 5,
    locked: true,
    maxSeat: 1,
    parentId: 40,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1485,
    statusId: 1,
    titleENG: 'The Monastery and the Provost',
    titleGER: 'Das Stift und der Propst',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1486,
    id: 4001,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 40,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1485,
    statusId: 1,
    titleENG: 'Sunthaym\'s research',
    titleGER: 'Sunthayms Forschungen',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1506,
    id: 4004,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 40,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1505,
    statusId: 1,
    titleENG: 'The Legend of the Veil',
    titleGER: 'Die Schleierlegende',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'Intro to section 5:',
    endDate: 1507,
    id: 5000,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 5,
    locked: true,
    maxSeat: 1,
    parentId: 50,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1506,
    statusId: 1,
    titleENG: 'Relocating the mortal remains',
    titleGER: 'Erhebung der Gebeine',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'tableNotifyAt',
    contents: [],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: 0,
    description: 'Genvis atLocation',
    endDate: 1507,
    id: 502,
    ipAddress: '10.10.11.6',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 9,
    locked: true,
    maxSeat: 2,
    parentId: 50,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1506,
    statusId: 2,
    titleENG: 'The Babenberg Pedigree',
    titleGER: 'Stammbaum der Babenberger',
    unlockCoa: true,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'Intro to section',
    endDate: 1520,
    id: 6000,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 5,
    locked: true,
    maxSeat: 1,
    parentId: 60,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1519,
    statusId: 1,
    titleENG: 'Commemoration',
    titleGER: 'Totengedenken',
    unlockCoa: true,
    updatedAt: '2019-09-10T21:34:01.000Z'
   },{
    contentURL: 'passive',
    contents: [],
    createdAt: '2019-09-10T21:34:01.000Z',
    currentSeat: null,
    description: 'passive exhibit',
    endDate: 1519.5,
    id: 6001,
    ipAddress: '0.0.0.0',
    isStartPoint: false,
    liked: false,
    locationTag: null,
    locationTypeId: 4,
    locked: true,
    maxSeat: 1,
    parentId: 60,
    positionId: null,
    showInTimeline: true,
    socketId: null,
    startDate: 1519,
    statusId: 1,
    titleENG: 'Death and legacy',
    titleGER: 'Tod und Erinnerung',
    unlockCoa: false,
    updatedAt: '2019-09-10T21:34:01.000Z'
   }];
